#ifndef ROSIDL_TYPESUPPORT_COREDDS_CPP__MESSAGE_TYPE_SUPPORT_DECL_HPP_
#define ROSIDL_TYPESUPPORT_COREDDS_CPP__MESSAGE_TYPE_SUPPORT_DECL_HPP_

#include <rosidl_generator_c/message_type_support_struct.h>
#include <rosidl_typesupport_coredds_cpp/visibility_control.h>

namespace rosidl_typesupport_coredds_cpp
{
template<typename T>
ROSIDL_TYPESUPPORT_COREDDS_CPP_PUBLIC
const rosidl_message_type_support_t* get_message_type_support_handle();
} // namespace rosidl_typesupport_coredds_cpp

#endif // ROSIDL_TYPESUPPORT_COREDDS_CPP__MESSAGE_TYPE_SUPPORT_DECL_HPP_
