#ifndef ROSIDL_TYPESUPPORT_COREDDS_CPP__SERVICE_TYPE_SUPPORT_DECL_HPP_
#define ROSIDL_TYPESUPPORT_COREDDS_CPP__SERVICE_TYPE_SUPPORT_DECL_HPP_

#include <rosidl_generator_c/service_type_support_struct.h>
#include <rosidl_typesupport_coredds_cpp/visibility_control.h>

namespace rosidl_typesupport_coredds_cpp
{

template<typename T>
ROSIDL_TYPESUPPORT_COREDDS_CPP_PUBLIC
const rosidl_service_type_support_t* get_service_type_support_handle();

}

#endif // ROSIDL_TYPESUPPORT_COREDDS_CPP__SERVICE_TYPE_SUPPORT_DECL_HPP_
